### ISSUE TITLE
R errors in blog post

### ISSUE THREAD

**Issue by eribul** [rOpenGov/sweidnumbr#113]
I noticed some R error messages from rendering our blog post from rOpenGov. http://ropengov.github.io/r/2015/08/20/sweidnumber/

**Comment by eribul** [comment]
I re-rendered the blog post and kept an .md-file but I think this file was previously send manually to someone at rOpenGov. I suspect @MansMeg knows everything about this :-)

**Comment by MansMeg** [comment]
Ok. Strange. Ill look at it when I have time. But that may take a while.

**Comment by MansMeg** [comment]
Ok. Sorry for not following up. @antagomir probably knows how this works.

**Comment by antagomir** [comment]
Right, thanks. Our rendering is indeed broken atm. We will need to fix. Let's keep this open for now, I aspire to return to it soon.

**Comment by eribul** [comment]
I close this issue since I interpret that the issue is not with this repo. Please feel free to re-open!
