### ISSUE TITLE
new_period was removed from lubridate

### ISSUE THREAD

**Issue by vspinu** [rOpenGov/sweidnumbr#114]
`new_period/interval` has been deprecated for several years now so we are finally removing it from `lubridate`. 

This broke the revdep [check](https://github.com/tidyverse/lubridate/blob/master/revdep/problems.md#sweidnumbr). 

Just replacing with the `period/interval` constructor should fix the problem. 

Sorry for the trouble.

**Comment by MansMeg** [comment]
Cool. Now fixed. Will update at CRAN when all tests pass. I changed it but got this message:

`Note: method with signature ‘Timespan#Timespan’ chosen for function ‘%/%’,
 target signature ‘Interval#Period’.
 "Interval#ANY", "ANY#Period" would also be valid`

Although all tests are still fine?

**Comment by vspinu** [comment]
Thanks for a quick fix. I The ambiguous dispatch warnings should have been fixed in lubridate devel. I have just run sweidnumbr tests and check locally and all is good.

**Comment by MansMeg** [comment]
Now submitted to CRAN.
