### ISSUE TITLE
Travis-CI to Github Actions 

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/sweidnumbr#118]
Old Travis-CI.org service will be shut down after 31th of December, requiring either action to migrate to the commercial Travis-CI.com service or migrating to a new CI altogether. An rOpenSci blogpost describes the pros of moving to GitHub Actions. The process is as follows:

run: `usethis::use_github_action_check_standard()`
Check if package tests contain skip_on_travis -functions and replace them with skip_on_ci
Add a badge to the package README: `[![R build status](https://github.com/rOpenGov/PACKAGENAME/workflows/R-CMD-check/badge.svg)](https://github.com/rOpenGov/PACKAGENAME/actions)`
Remove travis.yml (and appveyor.yml)
Remove Travis CI badge (and Appveyor badge, since GHA runs tests simultaneously for Linux, macOS and Windows)

**Comment by MansMeg** [comment]
Great!
