### ISSUE TITLE
fake_pins contain invalid checksum

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/sweidnumbr#123]
It is handy that sweidnumbr package has ```fake_pins``` dataset for testing purposes but it is unclear to me whether the PINs in this dataset should be structurally correct or not. It seems that a majority of these PINs have wrong check digits. Maybe this is due to changes to ```luhn_algo``` function?

Maybe the dataset could contain some wrong PINs as well and this could be clearly indicated in the man pages of the dataset. 

```
library(sweidnumbr)
pins <- as.pin(fake_pins$pin)
table(pin_ctrl(pins))

FALSE  TRUE 
   53     9 
```

**Comment by MansMeg** [comment]
I have not looked at this in detail, but I have test suites for the luhn algorithm so it should work as expected. Hence my guess is that these fake pins are incorrect. Although, lets keep this as an issue. Ill try to fix this when we get accepted during a release 1.0.

**Comment by MansMeg** [comment]
Yes. The data is original from the Swedish skatteverket. I add a note that many of these PINs has the wrong control digit.
