### ISSUE TITLE
Add verbose option to pin_age

### ISSUE THREAD

**Issue by soppen** [rOpenGov/sweidnumbr#126]
When calculating age from `pin` relative to another vector the console is flooded with message `The age is calculated relative to ... `. 

```
library(sweidnumbr)
N <- 100
data <- data.frame(pnr = rpin(N, end_date = "2000-01-01"))
data[["birthdate"]] <- pin_date(data[["pnr"]])
data[["visit_date"]] <- data[["birthdate"]] + sample(1:3650, size = N, replace = TRUE)
data[["age"]] <- pin_age(data[["pnr"]], data[["visit_date"]])
``` 

Suggest to add verbose option to `pin_age`, preferably `FALSE` by default, and set this message to only pring if explicitly requested by the user.

**Comment by MansMeg** [comment]
Sounds like a good idea. Thanks!

**Comment by MansMeg** [comment]
Now fixed in v. 1.5.0 (but the default is verbose). I also fixed so only one line is printed as a message.
