### ISSUE TITLE
Add more pin output formats

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/sweidnumbr#13]
pin_format kanske även kunde hantera character format med godtyckligt placerade ”-”, t ex ”YYYY-MMDD-NNNC” eller ”YY-YY-MMDD-NNNC” etc. Ibland vill man visa dem så av estetiska skäl för sekreterare som får långa listor att hantera etc.

**Comment by MansMeg** [comment]
Har du några synpunkter gällande detta @eribul ?

**Comment by eribul** [comment]
Jag tror den ursprungliga tanken egentligen handlade om hur man presenterar resultatet, dvs i mitt jobb gör man ibland kontroller av stora datamaterial. Hittar man några konstigheter så vill man skriva ut en lista som ges till en sekreterare som går igenom fallen och ev korrigerar i databasen.
Önskemålen är då ibland att personnumren skrivs ut i ett format som är lätt att läsa. 

I så fall skulle det kanske räcka att man kunde ge ett argument till `print.pin`-funktionen, dvs att pin alltid lagras på det vanliga sättet men ibland presenteras på ett annat sätt?

Annars om man har personnummer i formatet ovan som man vill använda vid anrop till as.pin kanske det går lika bra att användaren själv skriver t ex `as.pin(gsub("-", "", x))`?

**Comment by MansMeg** [comment]
Ah. Då tror jag det bästa är att vi lägger till ett arg, typ format till print som kan speca hur det ska skrivas ut. Låter vettigt. Typ YYYYMMDDNNNC.

**Comment by eribul** [comment]
Aha, just det men kanske är det föresten en `format.pin` vi skulle ha? 
Kanske då att man på ngt sätt lika väl kan försöka utöka den vanliga syntaxen för datumformat, typ:
`format(pin, "%Y%m%d%N)` (som nu)
`format(pin, "%Y-%m-%d-%N)` (för ett lite "luftigare" alternativ) etc

**Comment by MansMeg** [comment]
Det låter vettigt, men hur skulle vi då skriva ut det som du ville yy-yy-mmdd ex? Jag är lite dålig på denna R syntax. Men kan vi använda detta för att göra det du efterfrågar vore det ju grymt. Likaså borde man kunna speca informat på samma sätt.

**Comment by eribul** [comment]
Är inte heller ngn expert men det finns faktiskt ganska många olika standardformat, se `?strptime `, t ex för yy-yy-mmdd:

```{r}
> format(Sys.Date(), format = "%C-%y-%m%d")
[1] "20-15-0914"
```

Vet inte om det finns ngt standardiserat sätt för att specificera egna format etc men om man t ex säger att `%N` är förkortningen för de fyra sista siffrorna eller liknande så skulle man kanske först kunna bryta ut `%N` (samt ev prefix typ [:punct:] eller [:space:]) med regular expression och behandla separat, medan resten av strängen antas vara spec för datumdelen?

**Comment by MansMeg** [comment]
Nice. Låter som en vettig lösning! Med att vi lägger till egna format för löpnr och ctrl siffran!

**Comment by eribul** [comment]
Jag har (äntligen) tittat lite på detta. Själva funktionen är inte så svår att få till, typ:
```{r}
format.pin <- function(x, format. = "%Y%m%d%N", ...) {
  gsub_v <- Vectorize(gsub, "replacement")
  f <- gsub_v("%N", substr(x, 9, 12), format.)
  mapply(format, pin_to_date(x), f)
}
```

Dock blir det problem att definiera detta som en S3-metod till `print`-generikan (då vår pin-klass ju numer också innehåller "AsIs" och det finns en `format.AsIs` som hittas först). 
En lösning är att helt enkelt att skapa en fristående funktion `pin_format` istället men jag har också ställt en fråga på StackOverflow. Jag avvaktar ett slag och ser om det kanske dyker upp ngt bra förslag där:
http://stackoverflow.com/questions/33434865/how-to-make-s3-method-for-format-for-objects-with-class-including-asis

**Comment by MansMeg** [comment]
Grymt jobbat!
Försöker få lite reda i mina tankar nu bara:
Nu pratar vi bara om outputformat (d.v.s. class pin -> char). Isf tror jag pin_format() är en bra lösning, då kan vem som få ut ett format de tycker passar dem som en textvektor de sedan kan göra vad de vill med. Fixar du en funktion och en test_suite för detta?
 
Är det aktuellt med en motsvarande funktion char -> class pin? Jag tycker inte att det känns så. De fyra standardformaten finns redan så det borde folk kunna hantera själva?

**Comment by eribul** [comment]
Hittade nu en lösning för att kunna använda `format.pin`, vilket kanske trots allt är att föredra framför `pin_format` då det kanske är lite mer enligt praxis?

Jo, det blir ju character som output, vilket dock gäller generellt för `format`. Följande från `?format` under "Value"t:
> An object of similar structure to x containing character representations of the elements of the first argument x in a common format, and in the current locale's encoding.

> For character, numeric, complex or factor x, dims and dimnames are preserved on matrices/arrays and names on vectors: no other attributes are copied.

För t ex datum får man också:
```{r}
> format(Sys.Date())
[1] "2015-11-04"
> str(format(Sys.Date()))
 chr "2015-11-04"
```

Håller med om att det nog räcker så (i kombination med #32).
Jag har snart ett förslag i form av pull request!

**Comment by MansMeg** [comment]
Toppen!

**Comment by MansMeg** [comment]
Yay!
