### ISSUE TITLE
Testpersonnummer

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/sweidnumbr#24]
Kontakta Skatteverket för en lista med testpersonnummer att köra tester med.

Finns ngn nationell lista med fejkade personnummer t ex 121212121212 så kanske man kunde hårdkoda in att behandla dem lite speciellt?
http://sv.wikipedia.org/wiki/Tolvan_Tolvansson
http://www.dagensmedicin.se/nyheter/tolvan-tolvansson-smet-fran-skatteverket/
… finns kanske fler (på just vårt jobb har vi en hel lista med fejkade personnummer som vi använder för olika tester … vet inte om det är vår egen lista eller om det finns ngn nationell överenskommelse ang det) …

**Comment by eribul** [comment]
Jag inkluderade i pull request 8a9eead ett testdataset "fake_swedes" (laddas via LazyLoad) med fejkade namn och personnummer från en lista som används inom RCC. Även en kort hjälptext under `?fake_swedes`

**Comment by MansMeg** [comment]
Great! And Ive added the test_pin_skatteverket.csv file.

**Comment by niklasskoldmark** [comment]
Lessen om jag stör och öppnar upp en stängd issue. Men jag letade på GitHub efter ett färdigt python-lib för validering av testpersonnummer då dök denna tråd upp.
Ville bara tipsa om att det numera finns ett api för testpersonnummer på : https://skatteverket.entryscape.net/rowstore/dataset/b4de7df7-63c0-4e7e-bb59-1f156a591763/html

**Comment by MansMeg** [comment]
Tackar! En kort fråga, det verkar bara vara testpersonnummer från ett särskilt år (2017) vilket inte känns super?

**Comment by mansn** [comment]
@MansMeg I dagsläget går det iaf att få ut testpersonnummer mellan 1980-2020. 

Här är ett curl-exempel som hämtar testpersonnummer från 1980-1989 (regex `198.*`): 
```sh
curl -X GET "https://skatteverket.entryscape.net/rowstore/dataset/b4de7df7-63c0-4e7e-bb59-1f156a591763?testpersonnummer=198.*&_limit=100&_offset=0" -H "accept: application/json"
```

**Comment by MansMeg** [comment]
Tack!
