### ISSUE TITLE
Födelsenummer/folkbokföringsnummer

### ISSUE THREAD

**Issue by eribul** [rOpenGov/sweidnumbr#32]
## Bakgrund

Efter konsultation från vår byråassistent samt lite Googlingar tycks det som att personnummer visserligen infördes 1947 men då utan formell beteckning (kallades ibland Födelsenummer, ibland folkbokföringsnummer etc). Dessa nummer liknade dagens personnummer men saknade den sista kontrollsiffran. 

Först 1967 infördes personnummer såsom vi känner dem idag, inkl den sista siffran. Vid den tidpunkten beslutades också att alla individer "i Sverige" skulle få ett personnummer. För levande personer innebar det nog att det gamla födelsenumret/folkbokföringsnumret helt enkelt ersattes av ett nytt personnummer. Då slutade man använda det förra och det "föll lite i glömska".

Dock, enbart personer som levde 1967 verkar ha fått en korrekt uppdatering av sina nummer. 
I t ex cancerregistret (infört 1958) men uppdaterat kontinuerligt därefter, har man därför inte riktigt kunnat hantera personer levande efter 1947 men avlidna före 1967.
Detsamma tros gälla för övriga register som hanteras av Socialstyrelsen.
Socialstyrelsen beslutade då (vid ngn okänd tidpunkt, av ngn okänd person enl okänt dokument etc) att dessa personer fick behålla sitt födelsenummer men att man la till ett sista tecken för att få rätt antal tecken. Detta tecken är åtminstone i vår region nästan alltid ett "T" men i enstaka fall "A" eller "X" (oklar skillnad för min del men kanske SoS vet).

Jag benämnde tidigare dessa nummer som "reservnummer" men det var alltså felaktigt. Dessa nummer är i någon mening att betrakta som korrekta personnummer. Dock infördes ett nationellt historiskt folkbokföringsregister först 1969 så dessa nummer finns inte med där. När man härifrån (ihop med Socialstyrelsen) gjorde en genomgång av dessa nummer spårades de därför till kyrkoböckerna i respektive församling och inte till ngt nationellt register. Längre än så kom man aldrig utan man beslutade att inom SoS betrakta dessa nummer som giltiga personnummer. 

En del info finns här:
http://www.scb.se/statistik/_publikationer/BE9999_2007A01_BR_BE96ST0701.pdf

## Förslag
Att tillåta även detta som ett femte format i as.pin, dvs att om årtalet ligger före 1967 så accepteras att kontrollsiffran inte baseras på algoritmen utan är en bokstav (ev ett A, T eller X eller vilken bokstav som helst). Jag kan försöka höra mig för hos SoS ifall de har ngn mer dokumentation eller förklaring till vilket tecken som valts etc.

**Comment by MansMeg** [comment]
Har du hört något mer gällande detta @eribul ? Ska vi lägga till det?

**Comment by eribul** [comment]
Ska försöka fräscha upp minnet litegrann. Återkommer!

**Comment by eribul** [comment]
Tyvärr fick jag aldrig ngt ordentligt svar på min fråga till Sos. Jag har nu påmint dem igen. Under tiden tittade jag lite på hur man kanske skulle kunna lösa det men har inte skapat ngn pull request då det är prematurt. Just i mitt "case" har ju alla gamla nummer fått ett A, T eller X på slutet så det är bara just det jag inkluderat i 65503a7b2720df2d96c524ecede76042027b2f96 

Men om inte Sos svarar kanske detta ändå kan vara en lösning?

**Comment by MansMeg** [comment]
Vi behöver hitta någon referens som beskriver detta så vi vet vad vi inkluderar. Har vi bara det så tycker jag vi inkouderar. Men innan känns det dumt. Då blir det spekulativt. Borde det inte stå typ i någon gammal folkbokföringslag eller dyl?

Om du inte vet det så tycker jag vi kontaktar folkbokföringavdelningen på skatteverket. De måste veta.

/Måns

**Comment by eribul** [comment]
Instämmer! Fick nu f.ö. svar från Sos. De beklagar att de glömt svara men lovar titta på det igen och återkommer. 
Även Skatteverket låter ju som en lämplig kandidat att fråga! Verkar inte finnas så mkt info online (åtm inte som jag hittar via Google) men känner du till vem där man kan kontakta så låter ju det jättebra!

**Comment by MansMeg** [comment]
Jag har nu skickat en fråga till Skatteverket för att se om vi kan få napp därifrån.

**Comment by eribul** [comment]
Gôtt! Fick nu också svar från Sos:

> [...] Jag ser att kombinationerna finns med i cancerregistret ända fram till 1973. Har ingen bra förklaring än till varför dom finns med för diagnoser även efter 1967.
Har skickat frågan vidare till dödsorsaksregistret och ska höra mej för med dom andra registren.
Hos er och i Umeå förkommer ’A’ i den sista positionen i pnr men inte i de andra regionerna.
Återkommer när jag fått svar från de andra registeransvariga. [...]

**Comment by MansMeg** [comment]
Toppen!

Vore grymt om vi kunde lösa detta problem och hitta en referens.

**Comment by MansMeg** [comment]
Nu svar från skatteverket:
> Hej! Då tror jag att ni ska vända er till Riksarkivet där dem hanterar dem gamla folkbokföringsuppgifterna. Vi har enbart uppgifter från 1/7 1991 hos oss på Skatteverket.

Skickar vidare frågan till Riksarkivet.

**Comment by MansMeg** [comment]
Se svar från Riksarkivet. Kan du få tag i artikeln Wannerdt, Arvid, Den svenska folkbokföringen under tre sekler @eribul ?

___________________

Det finns ingen gammal räv som är expert på just personnummer. Vi har över 220 000 hyllmeter handlingar på Riksarkivet i Stockholm så vi kan inte vara experter på allt.

Det finns en informativ artikel i Årsbok för Riksarkivet och landsarkiven 1996 som heter "Folkbokföringen - historia och reform" av Karl-Gustaf Andersson. Där står det inget om just detta men det finns en lång källförteckning med artiklar och böcker om folkbokföringsfrågor, bla. hänvisas det till en artikel av Wannerdt, Arvid, Den svenska folkbokföringen under tre sekler, publicerad i RSV Riksskatteverket) Info åren 1979-82 som eventuellt kan ge svar.

Vi har även arkiven efter de myndigheter som bör ha handlagt dessa frågor nämligen Riksbyrån för folkbokföringen som verkade 1945-1964 samt Centrala folkbokförings- och uppbördsnämnden som bildades 1 juli 1964. Eventuellt skulle man kunna tänka sig att hitta information i Centrala folkbokförings- och uppbördsnämndens publikationer serierna under B3.

Ifall ni vill att vi letar i dessa arkiv så kostar eftersökning 150 kronor per påbörjad kvart och vi letar max en timme. Ni är även välkomna att besöka vår läsesal och själv leta i dessa arkiv.

**Comment by MansMeg** [comment]
Hittade den:
http://www.skatteverket.se/download/18.b7f2d0103e5e9ecb08000100/folkboforingens_historia.html

Står dock inget om det vi vill veta.

**Comment by MansMeg** [comment]
Jag har nu fått kontakt med de som kan folkbokföringsuppgifterna och precis som du skrev så var personnummer innan 1967 samma som dagens men utan kontrollsiffran. Kanske vi ska göra så att vi i as.pin tillåter felaktiga peronnummer (d.v.s. med godtyckligt sista siffra/textsnutt) men att as.pin då varnar om att kontrollsiffran är felaktig?

Jag har lagt till denna text i referenslistan och mejlat dig den.

**Comment by eribul** [comment]
Oj, missade tyvärr den längre posten ovan då den skrevs :-( Annars hade jag kanske kunnat be min bror (arkivarie som också tillbringat en del tid i landsarkiv etc om hjälp). Men kul att du hittade den ändå och intressant läsning! 

Ingenting hittills tyder ju i alla fall på att lösningen du beskriver skulle vara fel så jag tycker det låter som en bra idé!

**Comment by MansMeg** [comment]
Har uppdaterat dokumentationen nu i alla fall.

**Comment by MansMeg** [comment]
Yay!
