### ISSUE TITLE
Add pin from Skatteverket

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/sweidnumbr#33]
Add as a test data set. Calculate age, ctrl, coordn manually and use as test data.

**Comment by eribul** [comment]
8a9eead contains test data set "fake_swedes" with som e fake pins.

**Comment by MansMeg** [comment]
Great! Ive changed the pins to random pins from the Skatteverket file (in download raw). Renamed it to fake_pin instead (and updated your blog).

So there now exist a Skatteverket file with test pins that can be used.
