### ISSUE TITLE
Move to rOpenGov

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/sweidnumbr#54]

**Comment by MansMeg** [comment]
One more thing came to my mind on this: if you like you are welcome to write a blog post (short or long) on the new package. We can publish it in the rOpenGov blog. This supports Rmarkdown so the blog can be written as a fully reproducible Rmarkdown document even with some examples if you like.

**Comment by eribul** [comment]
I tried to write a draft as found in the pull request but feel free to change everything!

**Comment by MansMeg** [comment]
Great! Now Ive moved the repo to rOpenGov! can you publish the blog post?

**Comment by eribul** [comment]
Super! I'm happy you liked it! I just realise that we first might need to fix some references to the old account (the adress is mentioned in the blog post) but I'll create a separate issue for that!

**Comment by MansMeg** [comment]
Cool! Have you tried to publish the blog post on rOpenGov official blog?

**Comment by eribul** [comment]
Sorry for the veeeeeeeeery long delay ... but now I finally finished it and posted a request here: 
rOpenGov/ropengov.github.io/issues/6 

Not sure this was the correct way to do it but hope it will work :-)

**Comment by MansMeg** [comment]
Great job!
