### ISSUE TITLE
Change references from MansMeg to rOpenGov

### ISSUE THREAD

**Issue by eribul** [rOpenGov/sweidnumbr#57]
The adress is mentioned in README, in the blog post, as part of the travis picture URL, in the start up message when the package is loaded (and mayby somewhere else; I'll check).

**Comment by eribul** [comment]
Pull request  9f10798 fix most of this but I didn't dare to change the travis refernece in the README-file:

```{r}
[![Build Status](https://travis-ci.org/MansMeg/sweidnumbr.svg)](https://travis-ci.org/MansMeg/sweidnumbr)

```

**Comment by MansMeg** [comment]
Fixed!
