### ISSUE TITLE
Problem with recycling rules when pin vector used in data.frame

### ISSUE THREAD

**Issue by eribul** [rOpenGov/sweidnumbr#65]
The `data.frame` function usually allows argument of different lengths using recycling rules, for example:

```{r}
# Combining vectors of length 6 and 3 (automatically recycled)
> data.frame(letters[1:6], 1:3)
  letters.1.6. X1.3
1            a    1
2            b    2
3            c    3
4            d    1
5            e    2
6            f    3
``` 

These recycling rules does not apply to the pin class:
```{r}
> data.frame(letters[1:6], sweidnumbr::as.pin(c(191212121212, 192301011212)))
Error in data.frame(letters[1:6], sweidnumbr::as.pin(c(191212121212, 192301011212))) : 
  arguments imply differing number of rows: 6, 2
```

The reason is the following lines of code from `data.frame`
```{r}
...
                if (is.vector(xi1) || is.factor(xi1)) 
                  xi[[j]] <- rep(xi1, length.out = nr)
                else if (is.character(xi1) && inherits(xi1, "AsIs")) 
                  xi[[j]] <- structure(rep(xi1, length.out = nr), 
                    class = class(xi1))
                else if (inherits(xi1, "Date") || inherits(xi1, 
                  "POSIXct")) 
                  xi[[j]] <- rep(xi1, length.out = nr)
                else {
                  fixed <- FALSE
                  break
                }
        ...
        stop(gettextf("arguments imply differing number of rows: %s", 
            paste(unique(nrows), collapse = ", ")), domain = NA)
    }
```

Hence, the recycling rules are based on a sort of "white" list of classes and does not rely on class methods such as `as.data.frame.pin` etc.

One work around is to call the `data.frame` function with the pin vector wrapped in `I()`, hence:
```{r}
> data.frame(letters[1:6], I(sweidnumbr::as.pin(c(191212121212, 192301011212))))
  letters.1.6. sweidnumbr..as.pin.c.191212121212..192301011212..
1            a                                      191212121212
2            b                                      192301011212
3            c                                      191212121212
4            d                                      192301011212
5            e                                      191212121212
6            f                                      192301011212
```

I don'gt know however if this behaviour should maby be build in already from the beginning, hence, appending the class "AsIs" to the class attributes of pin such as:

```{}
as.pin <- function (pin) {
    I(UseMethod("as.pin"))
}
```
or similair.

On the other hand it can also be argued against use of R:s recycling rules. For example function `dplyr::data_frame` does not allow it at all:
```{r}
> dplyr::data_frame(letters[1:6], 1:3)
Error in data_frame_(lazyeval::lazy_dots(...)) : 
  arguments imply differing number of rows: 6, 3
```

**Comment by MansMeg** [comment]
What do you think? You now work more with pins than I do. Maybe the best is to stick to R recycling standards. Do your suggestion pass the tests?

Maybe send out this question on R development list?

**Comment by eribul** [comment]
I'll investigate a little more but I agree (following the standardd sounds great)!

I find the following methods for the "AsIs" class and I want to check that they do not have any side effects:
```{r}
> methods(class = "AsIs")
[1] [             as.data.frame format        print         xtfrm    
```
- [ ] [
- [ ] as.data.frame
- [ ] format
- [ ] print
- [ ] xtfrm

**Comment by MansMeg** [comment]
Great! I close this issue as well!
