### ISSUE TITLE
CRAN release 1.0?

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/sweidnumbr#81]
Are we satisfied enough with the package? Is there any small fixes left to do before we release it as a production version 1.0? What do you say Erik?

**Comment by eribul** [comment]
Not anything I can think of actually. I think we are ready to go!
A nice christmas gift to the world :-P

**Comment by MansMeg** [comment]
Great! Ill put it up today.

**Comment by MansMeg** [comment]
Great!

Im doing some small corrections. Adding you in citation file etc. So hopefully version 1.0 should be up soon!

**Comment by MansMeg** [comment]
Now everything is ready for submission to CRAN. Ive updated citation file, some small errors in the vignette etc. Can you check it a last time to see everything works fine for you?

/Måns

**Comment by eribul** [comment]
Exciting!
UnfortenAtely, I'm quite knocked out by a cold for the moment :(
I hope to be better soon but will have to wait a little.

**Comment by MansMeg** [comment]
No hurry. Ill wait til you have checked it, then I publish. Im working with a short paper right now.

**Comment by MansMeg** [comment]
Alright! Are you satisfied with the package? =)

**Comment by eribul** [comment]
Oh yes, very much indeed! :-)

**Comment by MansMeg** [comment]
Sent to CRAN now, just realised that we should have gone through the package api together before, now a lot of strange functions is exported to the package namespace that shouldn't be there. Removing them from the package makes the package not back compatible, so this needs to bump a major version. Doh.

**Comment by MansMeg** [comment]
```
Thanks, on CRAN now.

Best,
Uwe Ligges
```

Yay!

**Comment by eribul** [comment]
Woho, great! Merry Christmas :-)
