### ISSUE TITLE
Go through which functions to hide from API

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/sweidnumbr#83]
Now a large amount of functions is exported, even internal functions such as oin_group_element, pin_birthplace_internal, pin_coordn_correct and pin_century is now exported.

The api should also be added as a test in the test suite.

**Comment by eribul** [comment]
Hmm, are you sure? I don't actually see those functions in the `NAMESPACE` (or any`@export` statements in their Roxygen-comments). Or am I missing something?

**Comment by MansMeg** [comment]
Hmmm... Nej det verkar inte vara en del av API:et. Det är dock en del av dokumentationen så jag tolkade det som att de var exporterade till NAMESPACE. Detta är inte längre ngt problem. =)

**Comment by eribul** [comment]
Hehe jo, lite knepigt kanske. Men man kan t ex också låta bli att indexera just de hjälptexterna enligt citat nedan från:
https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html
(dvs man kan hitta dem om man vet att hjälpfunktionerna finns, t ex om man själv läser källkoden men man hittar dem inte via `help(package = "sweidnumbr")`).
Alternativt kan vi ju skippa dokumentationen också, tex byta ut `#'` mot bara `#` om vi ändå vill behålla det strukturerade formatet men bara som en del av källkoden för vår egen skull?

> @keywords keyword1 keyword2 ... to add standardised keywords. Keywords are optional, but if present, must be taken from the predefined list replicated in the keywords vignette. Keywords are not very useful, except for @keywords internal. Using the internal keyword removes all functions in the associated .Rd file from the documentation index and disables some of their automated tests. A common use case is to both export a function (using @export) and marking it as internal. That way, advanced users can access a function that new users would be confused about if they were to see it in the index.

**Comment by MansMeg** [comment]
Det låter vettigt att använda @keyword internal som lösning på problemet. Då kan man se till att dokumentationen inte indexeras men går att kolla på för mer avancerade användare och oss.

Lägger upp detta som en separat issue!
