### ISSUE TITLE
Remove stringr from dependencies

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/sweidnumbr#84]
We do not need to use stringr (unlike lubridate) so we should try to remove it from the dependencies.

**Comment by eribul** [comment]
I agree! I was even thinking about the actual need of lubridate when reading through but mayby that one is difficult to avoid?

**Comment by MansMeg** [comment]
I think we do not want to implement all the functionality that exists in lubridate so I suggest we still use it. BUT as you say, we should try to minimize the dependency so I suggest we move it to ```Suggests:``` instead of  ```Imports:```, then only people that want to use pin_age() or pin_to_date() will need to import lubridate. This keeps the dependency to an absolute minimum.

**Comment by MansMeg** [comment]
To handle numerical pins stringi function pad is used. This is implemented in C in a efficient manner so I gues we can' write more efficient code, so I suggest we keep the stringr dependency.
