### ISSUE TITLE
pin_ctrl(pin, force_logical = TRUE) doesn't return logic value

### ISSUE THREAD

**Issue by janzzon** [rOpenGov/sweidnumbr#92]
pin_ctrl() have problems to handle some wrong formated numbers. Example below.

``` r
sweidnumbr::pin_ctrl("19121212+1212", force_logical = TRUE)
#> Error in FUN(X[[i]], ...): All elements of x must have the same length with 9-12 digits!
```

I'll add a PR to development branch with updated tests/testthat/test-pin_ctrl.R to show this problem.

**Comment by MansMeg** [comment]
Solved now (version 1.1.1).
